function DataBaseWrite(handle,data)
    
COMMONDATA="CommonData";
COMMONDATAFRAME="CommonDataFrame";
DATAFRAMEANALOGSTN="DataFrameAnalogSTN";
DATAFRAMEPHASORSTN="DataFramePhasorSTN";
DATAFRAMESTN="DataFrameSTN";
     

    %Writring Common fields
    handle.sqlwrite(COMMONDATA, ...
        table(data.CommonData.FRAMESIZE.', ...
        data.CommonData.IDCODE.', ...
        data.CommonData.SOC.', ...
        data.CommonData.FRACSEC.', ...
        data.CommonData.SYNCFRAMETYPE.', ...
        data.CommonData.SYNCVERSION.', ...
        'VariableNames',["FRAMESIZE" "IDCODE" "SOC" "FRACSEC" "SYNCFRAMETYPE" "SYNCVERSION"]));

        %Writring Common dataframe fields
        handle.sqlwrite(COMMONDATAFRAME, ...
            table( ...
             data.CommonDataFrame.IDCODE.', ...
             data.CommonDataFrame.SOC.' ...
            ,data.CommonDataFrame.STN.' ...
            ,data.CommonDataFrame.STAT_DATA_ERROR.' ...
            ,data.CommonDataFrame.STAT_PMU_SYNC.' ...
            ,data.CommonDataFrame.STAT_DATA_SORTING.' ...
            ,data.CommonDataFrame.STAT_PMU_TRIGGER.' ...
            ,data.CommonDataFrame.STAT_CNF_CHANGE.' ...
            ,data.CommonDataFrame.STAT_DATA_MODIFIED.' ...
            ,data.CommonDataFrame.STAT_PMU_TQ.' ...
            ,data.CommonDataFrame.STAT_UNLOCKED_TIME.' ...
            ,data.CommonDataFrame.STAT_TRIGGER_REASON.', ...
            'VariableNames',["IDCODE" "SOC" "STN" "STAT_DATA_ERROR" "STAT_PMU_SYNC" "STAT_DATA_SORTING" "STAT_PMU_TRIGGER" "STAT_CNF_CHANGE" "STAT_DATA_MODIFIED" "STAT_PMU_TQ" "STAT_UNLOCKED_TIME" "STAT_TRIGGER_REASON"]));
    
    
        %Writring dataframe freq/dfreq fields
        handle.sqlwrite(DATAFRAMESTN, table( ...
            data.DataFrameSTN.IDCODE.', ...
            data.DataFrameSTN.SOC.', ...
            data.DataFrameSTN.STN.', ...
            data.DataFrameSTN.FREQ.', ...
            data.DataFrameSTN.DFREQ.', ...
            'VariableNames',["IDCODE" "SOC" "STN" "FREQ" "DFREQ"]));
   

                %Writring dataframe phasors fields
                handle.sqlwrite(DATAFRAMEPHASORSTN, ...
                    table( ...
                    data.DataFramePhasorSTN.IDCODE.', ...
                    data.DataFramePhasorSTN.SOC.', ...
                    data.DataFramePhasorSTN.STN.', ...
                    data.DataFramePhasorSTN.PHASOR_NAME.', ...
                    data.DataFramePhasorSTN.MAGNITUDE.', ...
                    data.DataFramePhasorSTN.PHASE.', ...
                    'VariableNames',["IDCODE" "SOC" "STN" "PHASOR_NAME" "MAGNITUDE" "PHASE"]));

                %Writring dataframe analog fields
                    
                handle.sqlwrite(DATAFRAMEANALOGSTN, ...
                    table( ...
                    data.DataFrameAnalogSTN.IDCODE.', ...
                    data.DataFrameAnalogSTN.SOC.', ...
                    data.DataFrameAnalogSTN.STN.', ...
                    data.DataFrameAnalogSTN.ANALOG_NAME.', ...
                    data.DataFrameAnalogSTN.ANALOG.', ...
                    'VariableNames',["IDCODE" "SOC" "STN" "ANALOG_NAME" "ANALOG"]));

commit(handle);
end

