%u = udpport("datagram","Ipv4","LocalPort",4713,"LocalHost","192.168.22.103","OutputDatagramSize",96);


%disp(u.NumDatagramsAvailable());
%data = read(u,1,"uint8");
load("testData.mat","data");
ParsedData=struct('SYNC',data.Data(1:2),...
                  'FRAMESIZE',data.Data(3:4),...
                  'IDCODE',data.Data(5:6),...
                  'SOC',data.Data(7:10),...
                  'FRACSEC',data.Data(11:14),...
                  'STAT',data.Data(15:16));

%delete(u);
%clear u;